# Generated by Django 5.1.6 on 2025-02-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargoTrabajador', models.CharField(max_length=255)),
                ('nombreTrabajador', models.CharField(max_length=255)),
                ('telTrabajador', models.CharField(max_length=255)),
                ('emailTrabajador', models.CharField(max_length=255)),
                ('perfilLaboral', models.CharField(max_length=450)),
                ('infoTrabajador', models.CharField(max_length=800)),
                ('codTrabajador', models.CharField(max_length=255)),
                ('imgTrabajador', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
