# Generated by Django 5.1.6 on 2025-02-23 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('trabajadores', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('idTickets', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fechaIncial', models.DateTimeField(auto_now_add=True)),
                ('fechaRespuesta', models.DateTimeField(blank=True, null=True)),
                ('codEmpresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='empresas.empresa')),
                ('codTrabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='trabajadores.trabajador')),
            ],
        ),
    ]
